#!/usr/bin/python3
# Import libraries and modules
from bs4 import BeautifulSoup as B
import re
import urllib
import os
import mysql.connector as my
from mysql.connector import Error
from mysql.connector import errorcode

####################### CHANGE THIS FOR DIFFERENT HTML FILES##############################
# put html into file variable and open it
html_file = "/home/jpie/Projects/python_workpace/Berlusconi/SOFTWARE & MALWARE/(27)All Products   BERLUSCONI MARKET.htm"
page = open(html_file)

# Create BS object
soup = B(page.read(), features='lxml')

# try to get vendor names and write them in a file
# open 'vendor.txt' file in write mode.
vendors = open("vendor.txt", "w")
# get the required information between the 'div' html tags
vendor_html = soup.find_all("div", class_="user-details")
vendor_html = str(vendor_html)

# begin loop to get vendor name and clean it
for i in re.findall(r'>\b\w+',vendor_html):
        vendors.write(i)
        vendors.write("\n")
        os.popen("sed 's/>//g' vendor.txt > vendors.txt")
#close file
vendors.close()

# find the product
product_html = soup.find_all("div", class_="item-details")
product_html = str(product_html)

# open 'products.txt' file in write mode
products = open("products.txt", "w")

# begin loop to get product detail and clean it
for i in re.findall(r'(?<=<b>)(.*?)(?=<\/b>)',product_html):
        products.write(i)
        products.write("\n")
#close file
products.close()

# find the prices
price_html = soup.find_all("strong")
price_html = str(price_html)

# open file for prices
prices = open("prices.txt", "w")

# looping again ....
for i in re.findall(r'(?<=<strong>)(.*?)(?=<b>)',price_html):
        prices.write(i)
        prices.write("\n")

prices.close()

#######################################################
##### GET RID OF UNEXPECTED COMMAS IN PRODUCT FILE ####
#######################################################
al_asad_talal = os.popen("sed 's/,/ /g' products.txt > product.txt")
# combine all the text files into a CSV file
al_asad_oh_la_la = os.popen("paste -d',' product.txt vendors.txt prices.txt > asad.csv")
al_asad_shan = os.popen("cp asad.csv /var/lib/mysql/BERLUSCONI_MARKET/asad.csv")

#MySQL stuff
try:
        conn = my.connect(
        host='localhost',
                user='root',
                passwd='123qweasdzxc',
                db='BERLUSCONI_MARKET'
        )
except ValueError:
        print("OH AL ASAD!!! DB ERROR!")
try:
        cursor = conn.cursor()
        query = '''load data local infile '/var/lib/mysql/BERLUSCONI_MARKET/asad.csv' into table Software_Malware fields terminated by ',';'''
        cursor.execute(query)
        conn.commit()
        conn.close()
except ValueError:
        print("OH YAYA !!!QUERY ERROR!")

####
# IM GOOD
###
salam = os.popen("rm /var/lib/mysql/BERLUSCONI_MARKET/asad.csv")
